<?php return array (
  'email_type' => '1',
  'email_safe' => '',
  'mail_address' => '',
  'smtp' => '',
  'smtp_user' => '',
  'smtp_pwd' => '',
  'smtp_port' => '',
  'order_by' => 'new',
  'name' => '天天题库学习平台',
  'url' => 'http://iweb.goat.msns.cn:5088',
  'master' => '',
  'qq' => '',
  'email' => '',
  'mobile' => '',
  'phone' => '',
  'address' => '',
  'site_footer_code' => '',
  'tax' => '10',
  'stockup_time' => '1',
  'index_seo_title' => '天天题库学习平台',
  'index_seo_keywords' => '天天题库学习平台',
  'index_seo_description' => '天天题库学习平台',
  'goods_no_pre' => 'SD',
  'commission' => '',
  'store_num_warning' => '1',
  'reg_option' => '0',
)?>